[project]
name = "netflix_rec_system"
version = "0.0.1"
authors = [
  { name="Debora", email="deboraellenss2@gmail.com" },
]
description = "A small example of netflix rec system"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"